nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  '@tanstack/router-devtools@*':
    peerDependencies:
      'csstype': '*'
  '@tanstack/eslint-plugin-query@*':
    peerDependencies:
      'typescript': '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      'typescript': '*'
