/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './../__root'
import { Route as IndexImport } from './../index'
import { Route as LocaleLoginRouteImport } from './../$locale/login/route'
import { Route as LocaleAboutRouteImport } from './../$locale/about/route'
import { Route as LocaleAuthRouteImport } from './../$locale/_auth/route'
import { Route as LocaleIndexRouteImport } from './../$locale/index/route'
import { Route as LocaleAuthProfileRouteImport } from './../$locale/_auth/profile/route'
import { Route as LocaleAuthDashboardRouteImport } from './../$locale/_auth/dashboard/route'

// Create Virtual Routes

const LocaleImport = createFileRoute('/$locale')()

// Create/Update Routes

const LocaleRoute = LocaleImport.update({
  path: '/$locale',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleLoginRouteRoute = LocaleLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any).lazy(() =>
  import('./../$locale/login/route.lazy').then((d) => d.Route),
)

const LocaleAboutRouteRoute = LocaleAboutRouteImport.update({
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any).lazy(() =>
  import('./../$locale/about/route.lazy').then((d) => d.Route),
)

const LocaleAuthRouteRoute = LocaleAuthRouteImport.update({
  id: '/$locale/_auth',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleIndexRouteRoute = LocaleIndexRouteImport.update({
  path: '/$locale/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../$locale/index/route.lazy').then((d) => d.Route),
)

const LocaleAuthProfileRouteRoute = LocaleAuthProfileRouteImport.update({
  path: '/profile',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any).lazy(() =>
  import('./../$locale/_auth/profile/route.lazy').then((d) => d.Route),
)

const LocaleAuthDashboardRouteRoute = LocaleAuthDashboardRouteImport.update({
  path: '/dashboard',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any).lazy(() =>
  import('./../$locale/_auth/dashboard/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_auth': {
      id: '/$locale/_auth'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/_auth/dashboard': {
      id: '/$locale/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleAuthDashboardRouteImport
      parentRoute: typeof LocaleAuthRouteImport
    }
    '/$locale/_auth/profile': {
      id: '/$locale/_auth/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleAuthProfileRouteImport
      parentRoute: typeof LocaleAuthRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LocaleIndexRouteRoute,
  LocaleRoute: LocaleRoute.addChildren({
    LocaleAuthRouteRoute: LocaleAuthRouteRoute.addChildren({
      LocaleAuthDashboardRouteRoute,
      LocaleAuthProfileRouteRoute,
    }),
    LocaleAboutRouteRoute,
    LocaleLoginRouteRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale/",
        "/$locale"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale/": {
      "filePath": "$locale/index/route.tsx"
    },
    "/$locale": {
      "filePath": "$locale/_auth",
      "children": [
        "/$locale/_auth",
        "/$locale/about",
        "/$locale/login"
      ]
    },
    "/$locale/_auth": {
      "filePath": "$locale/_auth/route.tsx",
      "parent": "/$locale",
      "children": [
        "/$locale/_auth/dashboard",
        "/$locale/_auth/profile"
      ]
    },
    "/$locale/about": {
      "filePath": "$locale/about/route.tsx",
      "parent": "/$locale"
    },
    "/$locale/login": {
      "filePath": "$locale/login/route.tsx",
      "parent": "/$locale"
    },
    "/$locale/_auth/dashboard": {
      "filePath": "$locale/_auth/dashboard/route.tsx",
      "parent": "/$locale/_auth"
    },
    "/$locale/_auth/profile": {
      "filePath": "$locale/_auth/profile/route.tsx",
      "parent": "/$locale/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
