/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about/route'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index/route'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAboutRouteRoute = LocaleAboutRouteImport.update({
  path: '/$locale/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$locale/about/route.lazy').then((d) => d.Route),
)

const LocaleIndexRouteRoute = LocaleIndexRouteImport.update({
  path: '/$locale/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$locale/index/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LocaleIndexRouteRoute,
  LocaleAboutRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale/",
        "/$locale/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale/": {
      "filePath": "$locale/index/route.tsx"
    },
    "/$locale/about": {
      "filePath": "$locale/about/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
